### ISSUE TITLE
Can't download ccdl.py shutil.py error

### ISSUE THREAD

**Issue by Matgen84** [chriswayg/CC-Offline-Package-Generator#6] opened 2021-06-10 08:11 UTC
Hi 

I download last release (July 2020). I can't download any Adobe CC 2021 software. Last month, there is a commit for update_icon path, but no CC-Offline-Package-Generator new dmg 

I've got the error message below.

Please help me.

macOS Catalina 10.15.7 19H1217

`sapCode: PHSP
version: 22.4.2
installLanguage: fr_FR
dest: /Users/mathieu/Desktop/Install PHSP_22.4.2-fr_FR.app

Creating Install PHSP_22.4.2-fr_FR.app
Traceback (most recent call last):
  File "ccdl.py", line 375, in <module>
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/app.icns'
[64328] Failed to execute script ccdl`

**Comment by inspiredearth** [comment] 2021-07-09 01:31
Regarding this 
```
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/app.icns'
```

See this [issue](https://github.com/chriswayg/CC-Offline-Package-Generator/issues/4). 

You can either edit the script, or more simply create a duplicate of the `CreativeCloudInstaller.icns` file, and rename the duplicate to `app.icns`.

**Comment by Drovosek01** [comment] 2021-08-01 17:17
Same problem
![image](https://user-images.githubusercontent.com/29478700/127779777-dcd2fc35-f636-40cc-9ab3-90003ffd40a1.png)

**Comment by chriswayg** [comment] 2022-03-10 18:24
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which packages the updated script _(version 0.1.4)_ by [Drovosek01](https://github.com/Drovosek01) / [adobe-packager](https://github.com/Drovosek01/adobe-packager), which can be found in the `src/` folder.

Download: [CC Offline Package Generator 0.1.4_1 ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Closed as completed by chriswayg** 2022-03-10 18:24 UTC

**Comment by chriswayg** [comment] 2022-03-13 07:42
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
